### ISSUE TITLE
Exception 'ReflectionException' with message 'Class user does not exist'

### ISSUE THREAD

**Issue by fimak** [mdmsoft/yii2-admin#39]
I've installed this module and when I try to use console I get error:

```
Exception 'ReflectionException' with message 'Class user does not exist'

in /home/fimak/web/tradesimple/vendor/yiisoft/yii2/di/Container.php:408

Stack trace:
#0 /home/fimak/web/tradesimple/vendor/yiisoft/yii2/di/Container.php(408): ReflectionClass->__construct('user')
#1 /home/fimak/web/tradesimple/vendor/yiisoft/yii2/di/Container.php(354): yii\di\Container->getDependencies('user')
#2 /home/fimak/web/tradesimple/vendor/yiisoft/yii2/di/Container.php(147): yii\di\Container->build('user', Array, Array)
#3 /home/fimak/web/tradesimple/vendor/yiisoft/yii2/di/Instance.php(146): yii\di\Container->get('user')
#4 /home/fimak/web/tradesimple/vendor/yiisoft/yii2/di/Instance.php(120): yii\di\Instance->get(NULL)
#5 /home/fimak/web/tradesimple/vendor/mdmsoft/yii2-admin/components/AccessControl.php(33): yii\di\Instance::ensure('user', 'yii\web\User')
#6 /home/fimak/web/tradesimple/vendor/yiisoft/yii2/base/Object.php(107): mdm\admin\components\AccessControl->init()
#7 [internal function]: yii\base\Object->__construct(Array)
#8 /home/fimak/web/tradesimple/vendor/yiisoft/yii2/di/Container.php(364): ReflectionClass->newInstanceArgs(Array)
#9 /home/fimak/web/tradesimple/vendor/yiisoft/yii2/di/Container.php(147): yii\di\Container->build('mdm\admin\compo...', Array, Array)
#10 /home/fimak/web/tradesimple/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('mdm\admin\compo...', Array, Array)
#11 /home/fimak/web/tradesimple/vendor/yiisoft/yii2/base/Component.php(180): yii\BaseYii::createObject(Array)
#12 /home/fimak/web/tradesimple/vendor/yiisoft/yii2/BaseYii.php(518): yii\base\Component->__set('as access', Array)
#13 /home/fimak/web/tradesimple/vendor/yiisoft/yii2/base/Object.php(105): yii\BaseYii::configure(Object(yii\console\Application), Array)
#14 /home/fimak/web/tradesimple/vendor/yiisoft/yii2/base/Application.php(202): yii\base\Object->__construct(Array)
#15 /home/fimak/web/tradesimple/vendor/yiisoft/yii2/console/Application.php(79): yii\base\Application->__construct(Array)
#16 /home/fimak/web/tradesimple/yii(29): yii\console\Application->__construct(Array)
#17 {main}
```

/common/config/main.php

```
return [
    'vendorPath' => dirname(dirname(__DIR__)) . '/vendor',
    'extensions' => require(__DIR__ . '/../../vendor/yiisoft/extensions.php'),
    'components' => [
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'authManager' => [
            'class' => 'yii\rbac\DbManager',
        ],
    ],
    'modules'=>[
        'admin' => [
            'class' => 'mdm\admin\Module',
        ],
    ],
    'as access' => [
        'class' => 'mdm\admin\components\AccessControl',
        'allowActions' => [
            'admin/*',
        ],
    ],
];
```

**Comment by richfuns** [comment]
Many Thanks. solved.
